name: tomo.place

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./docs/spring/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tomo-network
    depends_on:
      - db

  db:
    container_name: db
    build:
      context: ./docs/postgres
      dockerfile: Dockerfile
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - tomo-network

networks:
  tomo-network:
    driver: bridge
