-- liquibase formatted sql

-- changeset ian:1758206625942-1
CREATE TABLE public.place (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, address VARCHAR(255) NOT NULL, address_detail VARCHAR(255), created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(6) WITHOUT TIME ZONE, entity_id UUID NOT NULL, external_id VARCHAR(255) NOT NULL, location GEOMETRY NOT NULL, name VARCHAR(255) NOT NULL, search_vector TSVECTOR, sub_category VARCHAR(255), type VARCHAR(255) NOT NULL, updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, CONSTRAINT "placePK" PRIMARY KEY (id));

-- changeset ian:1758206625942-2
CREATE TABLE public.place_folder (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, default_name VARCHAR(20) NOT NULL, deleted_at TIMESTAMP(6) WITHOUT TIME ZONE, owner_id BIGINT NOT NULL, tags TEXT[], updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, visibility VARCHAR(255) NOT NULL, CONSTRAINT "place_folderPK" PRIMARY KEY (id));

-- changeset ian:1758206625942-3
CREATE TABLE public.place_folder_item (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, created_by_user_id BIGINT NOT NULL, deleted_at TIMESTAMP(6) WITHOUT TIME ZONE, "order" INTEGER, updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, folder_id BIGINT NOT NULL, place_id BIGINT NOT NULL, CONSTRAINT "place_folder_itemPK" PRIMARY KEY (id));

-- changeset ian:1758206625942-4
CREATE TABLE public.place_folder_permission (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(6) WITHOUT TIME ZONE, granted_by BIGINT NOT NULL, permissions JSONB NOT NULL, updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, user_id BIGINT NOT NULL, folder_id BIGINT NOT NULL, CONSTRAINT "place_folder_permissionPK" PRIMARY KEY (id));

-- changeset ian:1758206625942-5
CREATE TABLE public.place_folder_setting (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(6) WITHOUT TIME ZONE, icon_color VARCHAR(255) NOT NULL, is_display_stored_place BOOLEAN NOT NULL, is_display_visited_place BOOLEAN NOT NULL, name VARCHAR(255) NOT NULL, updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, user_id BIGINT NOT NULL, folder_id BIGINT NOT NULL, CONSTRAINT "place_folder_settingPK" PRIMARY KEY (id));

-- changeset ian:1758206625942-6
ALTER TABLE public.place ADD CONSTRAINT uq_place__entity_id UNIQUE (entity_id);

-- changeset ian:1758206625942-7
ALTER TABLE public.place_folder_item ADD CONSTRAINT uq_place_folder_item__folder_id_place_id UNIQUE (folder_id, place_id);

-- changeset ian:1758206625942-8
ALTER TABLE public.place_folder_permission ADD CONSTRAINT uq_place_folder_permission__user_id_place_folder_id UNIQUE (user_id, folder_id);

-- changeset ian:1758206625942-9
ALTER TABLE public.place_folder_setting ADD CONSTRAINT uq_place_folder_setting__user_id_folder_id UNIQUE (user_id, folder_id);

-- changeset ian:1758206625942-10
CREATE INDEX idx_place__location_gist ON public.place(location);

-- changeset ian:1758206625942-11
CREATE INDEX idx_place__search_vector ON public.place(search_vector);

-- changeset ian:1758206625942-12
CREATE INDEX idx_place__type ON public.place(type);

-- changeset ian:1758206625942-13
CREATE INDEX idx_place_folder__deleted ON public.place_folder(deleted_at);

-- changeset ian:1758206625942-14
CREATE INDEX idx_place_folder__owner ON public.place_folder(owner_id);

-- changeset ian:1758206625942-15
CREATE INDEX idx_place_folder__tags ON public.place_folder(tags);

-- changeset ian:1758206625942-16
CREATE INDEX idx_place_folder_item__created_by_user_id ON public.place_folder_item(created_by_user_id);

-- changeset ian:1758206625942-17
CREATE INDEX idx_place_folder_item__folder_id ON public.place_folder_item(folder_id);

-- changeset ian:1758206625942-18
CREATE INDEX idx_place_folder_item__folder_id_order ON public.place_folder_item(folder_id, "order");

-- changeset ian:1758206625942-19
CREATE INDEX idx_place_folder_item__place_id ON public.place_folder_item(place_id);

-- changeset ian:1758206625942-20
CREATE INDEX idx_place_folder_permission__folder_id ON public.place_folder_permission(folder_id);

-- changeset ian:1758206625942-21
CREATE INDEX idx_place_folder_permission__type ON public.place_folder_permission(permissions);

-- changeset ian:1758206625942-22
CREATE INDEX idx_place_folder_permission__user_id ON public.place_folder_permission(user_id);

-- changeset ian:1758206625942-23
ALTER TABLE public.place_folder_permission ADD CONSTRAINT "FK21yf13mp2wfvtk7teibyrt4tm" FOREIGN KEY (folder_id) REFERENCES public.place_folder (id);

-- changeset ian:1758206625942-24
ALTER TABLE public.place_folder_item ADD CONSTRAINT "FKd1sovl3iu3uftq1vnqgtj0jhf" FOREIGN KEY (folder_id) REFERENCES public.place_folder (id);

-- changeset ian:1758206625942-25
ALTER TABLE public.place_folder_setting ADD CONSTRAINT "FKncyjd6oeqog8knpag9ch83lsd" FOREIGN KEY (folder_id) REFERENCES public.place_folder (id);

-- changeset ian:1758206625942-26
ALTER TABLE public.place_folder_item ADD CONSTRAINT "FKpuu91jcikdothh2cv27hj3oi7" FOREIGN KEY (place_id) REFERENCES public.place (id);

