oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
    token-uri: "https://oauth2.googleapis.com/token"
    user-info-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
  
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: "https://kauth.kakao.com/oauth/token"
    user-info-uri: "https://kapi.kakao.com/v2/user/me"
  
  apple:
    client-id: ${APPLE_CLIENT_ID}
    key-id: ${APPLE_KEY_ID}
    team-id: ${APPLE_TEAM_ID}
    key-path: ${APPLE_KEY_PATH}
    redirect-uri: ${APPLE_REDIRECT_URI}
    token-uri: "https://appleid.apple.com/auth/token"
    user-info-uri: "https://appleid.apple.com/auth/userinfo" 