-- liquibase formatted sql

-- changeset ian:1758200512229-1
CREATE TABLE public.users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(6) WITHOUT TIME ZONE, email VARCHAR(255) NOT NULL, entity_id UUID NOT NULL, nickname VARCHAR(255), status VARCHAR(255), updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, username VARCHAR(255) NOT NULL, CONSTRAINT "usersPK" PRIMARY KEY (id));

-- changeset ian:1758200512229-2
ALTER TABLE public.users ADD CONSTRAINT uq_user__email UNIQUE (email);

-- changeset ian:1758200512229-3
ALTER TABLE public.users ADD CONSTRAINT uq_user__entity_id UNIQUE (entity_id);
