-- liquibase formatted sql

-- changeset ian:1758198130778-1
CREATE TABLE public.social_account (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, email VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, name VARCHAR(255), profile_image_url VARCHAR(255), provider VARCHAR(255) NOT NULL, social_id VARCHAR(255) NOT NULL, updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, user_id BIGINT NOT NULL, CONSTRAINT "social_accountPK" PRIMARY KEY (id));

-- changeset ian:1758198130778-2
ALTER TABLE public.social_account ADD CONSTRAINT uq_social_account__provider_social_id UNIQUE (provider, social_id);

-- changeset ian:1758198130778-3
ALTER TABLE public.social_account ADD CONSTRAINT fk_social_account__user_id FOREIGN KEY (user_id) REFERENCES users (id);
