name: Flutter Tests

on:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/flutter-test.yml'
  pull_request:
    paths:
      - 'app/**'

jobs:
  test:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Run Tests with Coverage
        run: flutter test --coverage

      - name: Convert lcov paths (monorepo)
        if: always()
        run: |
          sed -i '' 's#SF:lib/#SF:app/lib/#g' coverage/lcov.info || true

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-coverage
          path: app/coverage/lcov.info


